# Backup configuration
SOURCE_DIR:
  - "/path/to/source/directory1"
  - "/path/to/source/directory2"
SOURCE_DIR_NAME: "myfiles"
SCHEDULE: "0 2 * * *"
EXCLUDE:
  - "*.tmp"
  - "node_modules"
NAS_PATH: "/mnt/nas/backups"
LOCAL_TMP: "/tmp/backup_tmp"
LOG_FILE: "/var/log/backup.log"
RETENTION_DAYS: 7
PYTHON: "/usr/bin/python3"
EMAIL:
  ENABLED: true
  TO: "your@email.com"
  FROM: "backup@email.com"
  SMTP_SERVER: "smtp.example.com"
  SMTP_PORT: 587
  USER: "smtpuser"
  PASS: "smtppassword"